Repository Clock24-SV/frontend, pull requests merged in 2024-03, with the labels that each got.

#2 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서수정

#4 feat: 로그인 퍼블리싱 및 기능 구현
  .gitignore
  package-lock.json
  package.json
  src/app/(main)/index.module.scss
  src/app/(main)/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/.keep
  src/components/KakaoLoginButton/index.module.scss
  src/components/KakaoLoginButton/index.tsx
  src/providers/.keep
  src/styles/globalStyle.scss
Labels: 기능구현, 퍼블리싱

#5 design : nav바 퍼블리싱
  package-lock.json
  package.json
  src/app/(main)/page.tsx
  src/app/todo/index.module.scss
  src/app/todo/page.tsx
  src/assets/Images/nav-logo.svg
  src/common/Nav/index.module.scss
  src/common/Nav/index.tsx
  src/common/RImage/index.tsx
  src/styles/globalStyle.scss
  src/styles/media.scss
Labels: 퍼블리싱
