Repository Clock24-SV/frontend, pull requests merged in 2024-04, with the labels that each got.

#6 [feat] 투두리스트 퍼블리싱
  src/app/(todo)/layout.tsx
  src/app/(todo)/main/index.module.scss
  src/app/(todo)/main/page.tsx
  src/assets/Images/noCloud.svg
  src/assets/Images/noRain.svg
  src/assets/Images/noSun.svg
  src/assets/Images/rain.svg
  src/assets/Images/sun.svg
  src/assets/Images/todoPercent.svg
  src/components/Todo/Day/index.module.scss
  src/components/Todo/Day/index.tsx
  src/components/Todo/Progressive/index.module.scss
  src/components/Todo/Progressive/index.tsx
  src/components/Todo/Schedule/index.module.scss
  src/components/Todo/Schedule/index.tsx
  src/components/Todo/TodoLists/ClearButton/index.module.scss
  src/components/Todo/TodoLists/ClearButton/index.tsx
  src/components/Todo/TodoLists/DeleteButton/index.module.scss
  src/components/Todo/TodoLists/DeleteButton/index.tsx
  src/components/Todo/TodoLists/TodoData/index.module.scss
  src/components/Todo/TodoLists/TodoData/index.tsx
  src/components/Todo/TodoLists/index.module.scss
  src/components/Todo/TodoLists/index.tsx
  src/components/Todo/index.module.scss
  src/components/Todo/index.tsx
  src/constants/todo.ts
  src/hooks/useTodo.ts
  src/utils/Todo/todoData.ts
Labels: 퍼블리싱

#7 [design] Calendar, Timer 퍼블리싱
  next.config.mjs
  package-lock.json
  package.json
  src/app/(main)/index.module.scss
  src/app/(main)/page.tsx
  src/app/(todo)/layout.tsx
  src/app/(todo)/todo/index.module.scss
  src/app/(todo)/todo/page.tsx
  src/components/CountdownTimer/index.module.scss
  src/components/CountdownTimer/index.tsx
  src/components/KakaoLoginButton/index.tsx
  src/components/TodoCalendar/index.module.scss
  src/components/TodoCalendar/index.tsx
  src/constants/TimerMessage.tsx
  src/styles/calender.scss
  src/styles/globalStyle.scss
  src/utils/.keep
  src/utils/timeCalculate.ts
Labels: 퍼블리싱

#8 [design] calendar/todo 반응형 레이아웃 수정
  src/app/(todo)/main/index.module.scss
  src/app/(todo)/main/page.tsx
  src/app/(todo)/todo/index.module.scss
  src/app/(todo)/todo/page.tsx
  src/components/CountdownTimer/index.module.scss
  src/components/Title/index.module.scss
  src/components/Title/index.tsx
  src/components/Todo/TodoLists/ClearButton/index.module.scss
  src/components/Todo/TodoLists/DeleteButton/index.module.scss
  src/components/Todo/index.module.scss
  src/components/TodoCalendar/index.module.scss
Labels: 퍼블리싱

#10 [chore] express mongodb setting
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/constants/.keep
  backend/src/controllers/.keep
  backend/src/db/mongoClient.ts
  backend/src/index.ts
  backend/src/models/todos.ts
  backend/src/models/users.ts
  backend/src/routes/todos.ts
  backend/src/routes/users.ts
  backend/src/utils/.keep
  backend/tsconfig.json
Labels: 환경설정

#12 [feat]: mongodb에 유저 데이터 저장 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/api/auth/[...nextauth]/route.ts
  frontend/src/components/KakaoLoginButton/index.tsx
  frontend/src/lib/.keep
  frontend/src/lib/mongoClient.ts
Labels: 기능구현, 환경설정

#13 [chore] RN 환경설정
  frontend-app/.gitignore
  frontend-app/app.json
  frontend-app/babel.config.js
  frontend-app/package-lock.json
  frontend-app/package.json
  frontend-app/src/app/(tabs)/_layout.tsx
  frontend-app/src/app/(tabs)/index.tsx
  frontend-app/src/app/(tabs)/two.tsx
  frontend-app/src/app/+html.tsx
  frontend-app/src/app/+not-found.tsx
  frontend-app/src/app/_layout.tsx
  frontend-app/src/assets/fonts/Jua-Regular.ttf
  frontend-app/src/assets/fonts/SpaceMono-Regular.ttf
  frontend-app/src/assets/images/adaptive-icon.png
  frontend-app/src/assets/images/config.svg
  frontend-app/src/assets/images/favicon.png
  frontend-app/src/assets/images/friend-list.svg
  frontend-app/src/assets/images/home.svg
  frontend-app/src/assets/images/icon.png
  frontend-app/src/assets/images/logo.png
  frontend-app/src/assets/images/logo.svg
  frontend-app/src/assets/images/moon.svg
  frontend-app/src/assets/images/profile.svg
  frontend-app/src/assets/images/search.svg
  frontend-app/src/assets/images/splash.png
  frontend-app/src/assets/images/sun.svg
  frontend-app/src/common/CustomButton.tsx
  frontend-app/src/common/CustomText.tsx
  frontend-app/src/common/CustomTextInput.tsx
  frontend-app/src/components/ExternalLink.tsx
  frontend-app/src/components/Themed.tsx
  frontend-app/src/components/__tests__/StyledText-test.js
  frontend-app/src/components/useClientOnlyValue.ts
  frontend-app/src/components/useClientOnlyValue.web.ts
  frontend-app/src/components/useColorScheme.ts
  frontend-app/src/components/useColorScheme.web.ts
  frontend-app/src/constants/Colors.ts
  frontend-app/src/styles/GlobalStyle.tsx
  frontend-app/src/styles/theme.ts
  frontend-app/tsconfig.json
Labels: 환경설정

#14 [design] 로그인 페이지 퍼블리싱
  frontend-app/src/app/(tabs)/_layout.tsx
  frontend-app/src/app/Login/_layout.tsx
  frontend-app/src/app/_layout.tsx
  frontend-app/src/components/Themed.tsx
  frontend-app/src/constants/Colors.ts
  frontend-app/src/navigations/root/RootNavigator.tsx
  frontend-app/src/navigations/stack/AuthStackNavigator.tsx
  frontend-app/src/navigations/stack/StackNavigator.tsx
Labels: 퍼블리싱

#15 [design] header/tap 공용 컴포넌트 구현
  frontend-app/src/app/(tabs)/Config/_layout.tsx
  frontend-app/src/app/(tabs)/FriendList/_layout.tsx
  frontend-app/src/app/(tabs)/FriendSearch/_layout.tsx
  frontend-app/src/app/(tabs)/_layout.tsx
  frontend-app/src/app/(tabs)/index.tsx
  frontend-app/src/app/(tabs)/two.tsx
  frontend-app/src/assets/images/Config.png
  frontend-app/src/assets/images/FriendAdd.png
  frontend-app/src/assets/images/Home.png
  frontend-app/src/assets/images/Search.png
  frontend-app/src/assets/images/profile.png
  frontend-app/src/common/Header.tsx
  frontend-app/src/constants/tab.ts
  frontend-app/src/navigations/root/RootNavigator.tsx
Labels: 퍼블리싱

#16 [design] 친구 목록/ 친구 찾기 퍼블리싱
  frontend-app/package-lock.json
  frontend-app/package.json
  frontend-app/src/app/(tabs)/FriendList/_layout.tsx
  frontend-app/src/app/(tabs)/FriendSearch/_layout.tsx
  frontend-app/src/app/(tabs)/index.tsx
  frontend-app/src/app/Login/_layout.tsx
  frontend-app/src/assets/images/check.png
  frontend-app/src/assets/images/close.png
  frontend-app/src/assets/images/plus.png
  frontend-app/src/common/CustomButton.tsx
  frontend-app/src/common/CustomTextInput.tsx
  frontend-app/src/components/FriendListScreen/FrinedList/Button/index.tsx
  frontend-app/src/components/FriendListScreen/FrinedList/Introduce/index.tsx
  frontend-app/src/components/FriendListScreen/FrinedList/Profile/index.tsx
  frontend-app/src/components/FriendListScreen/FrinedList/Title/index.tsx
  frontend-app/src/components/FriendListScreen/FrinedList/index.tsx
  frontend-app/src/components/FriendListScreen/ToggleBox.tsx
  frontend-app/src/components/FriendSearchScreen/index.tsx
  frontend-app/src/constants/Colors.ts
  frontend-app/src/constants/search.ts
  frontend-app/src/hooks/FriendSearchScreen/useSearch.ts
  frontend-app/src/hooks/useInput.ts
  frontend-app/src/utils/friendSearch.ts
Labels: 퍼블리싱

#17 [design] 환경설정 페이지 퍼블리싱
  frontend-app/src/app/(tabs)/Config/_layout.tsx
Labels: 퍼블리싱

#18 [design] 메인 페이지 퍼블리싱
  frontend-app/package-lock.json
  frontend-app/package.json
  frontend-app/src/app/(tabs)/_layout.tsx
  frontend-app/src/app/(tabs)/index.tsx
  frontend-app/src/app/Login/_layout.tsx
  frontend-app/src/common/CustomButton.tsx
  frontend-app/src/components/Timer/index.tsx
  frontend-app/src/components/Todo/ProgressBar/index.tsx
  frontend-app/src/components/Todo/TodoList/TodoItem/index.tsx
  frontend-app/src/components/Todo/TodoList/index.tsx
  frontend-app/src/components/Todo/index.tsx
  frontend-app/src/constants/Calendar.ts
  frontend-app/src/constants/State.ts
  frontend-app/src/hooks/useTodo.ts
  frontend-app/src/types/todo.ts
  frontend-app/src/utils/calculateTimeLeft.ts
  frontend-app/src/utils/formatDate.ts
  frontend-app/src/utils/formatTimeLeft.ts
  frontend-app/src/utils/index.ts
Labels: 퍼블리싱
